### ISSUE TITLE
Create hard links does not work under Win 10

### ISSUE THREAD

**Issue by KriegerJoshua** [BellCrow/Minecraft_TurtleApi#3]
The script for creating hard links inside of your computer folder, does not seem to work under Win 10.

Reproduce:
Follow steps in the "Getting started". Then there is an error during script execution.

TODO : Find out what that error is exactly and add that here

**Comment by BellCrow** [comment]
The error was, that the os module, does not contain a symlink method

I have forgotten to document, that the pywin32 package is needed for the python script to function.
